### ISSUE TITLE
How to detect when MainWindow animator is complete?

### ISSUE THREAD

**Issue by TheJamesMachine** [QuantumTekSupport/SimpleMenu#2]
I have a bit of code that sets Button.Select() on the first button in the menu. If I leave the menu open on scene load, the code fires and the button is selected. If I hide the menu on scene load, then open it on key stroke, the button is not selected. 

I added an additional call to Button.Select() after the call to ToggleMenu(true), but the button still isn't selected. I'm thinking there is a timing issue, since the menu opens and closes with an animator.

I tried using a coroutine waiting for SM_Window.active to change, but in code, it looks like that is changed before the animator is called.

Thanks for looking!

* Editing after the fact to say thanks for this free asset! I'm really looking forward to getting it implemented.

**Comment by QuantumTekSupport** [comment]
Thank you for your feedback! If you are wanting to call a function at the end of an animation, you can add an [AnimationEvent](https://docs.unity3d.com/Manual/script-AnimationWindowEvent.html) to the last frame of the animation. Could you show your code so I can further understand your problem?

**Comment by TheJamesMachine** [comment]
Thanks for replying. I haven't worked with animators before, so I will do some further research on that. This is what's going on in my code:

I have a menu script on a Simple Pause Menu that calls the following on Cancel axis input:

`menu.ToggleMenu(true);
wlsButtonManager.SelectCurrentButton();`

menu, of course, is a reference to SM_Menu. wlsButtonManager is a reference to a script on another game object in the hierarchy that handles targeting and highlighting UI buttons in the scene. This is the code in SelectCurrentButton:

`foreach (var btn in wlsButtons)
{
   if (btn.HasFocus)
   {
      btn.Select();
      break;
   }
}`

HasFocus is a bool property in a script on each button that sets which button has focus and is highlighted by default.

The issue I'm having is the button.Select() isn't happening. The rest of the code in WLSButtonManager does work (navigating through the buttons and highlighting the current button, etc). As mentioned earlier, the same code is called in WLSButtonManager.Start() and it works when I leave the menu open in the scene when it loads rather than calling ToggleMenu(false) in the Start() of the menu script. 

Not that it matters, but WLSButtonManager is a package of mine that is currently pending approval in the Asset Store. 

Hope that clears it up and thanks again for looking.
James

**Comment by QuantumTekSupport** [comment]
Okay. It seems like the button you want to select doesn't have focus when the menu is inactive. This could be because Unity's EventSystem doesn't select inactive UI elements (I believe), and therefore doesn't select the button when you turn it off immediately. In this case, I would recommend using an AnimatorEvent to give focus to the button (however that works in your package) when the animation is done.

**Comment by TheJamesMachine** [comment]
Thanks. I will research that further.

**Comment by TheJamesMachine** [comment]
As you said, it seems to be deep in the UI EventSystem behavior. Here's a Unity Answers thread from 2016 about this complete with a workaround calling SetSelectedGameObject(null) before selecting the button. Works great.

[https://answers.unity.com/questions/1142958/buttonselect-doesnt-highlight.html?page=1&pageSize=5&sort=votes](https://answers.unity.com/questions/1142958/buttonselect-doesnt-highlight.html?page=1&pageSize=5&sort=votes)

Case closed. Thanks for your patience.

**Comment by QuantumTekSupport** [comment]
Glad you were able to fix it.
